### ISSUE TITLE
Enhancement/Future Version Idea: Right sidebar version of this theme

### ISSUE THREAD

**Issue by KiKaraage** [sirlan-ff00ff/arcticfox-theme#16]
I kinda want to know how the experience would be if we had the sidebar on the right side, instead.

**Comment by sirlan-ff00ff** [comment]
At least from my looking around the browser's UI structure, it would be a bit more harder, as in the structure the header/widget bar and sidebar appear before the main content, and because CSS kinda defaults to 'left to right', those being on the left let you have to do less custom positioning. It's not impossible, just, out of scope for this (which is mainly for my use and to mimic Arc, which doesn't let you have a right sidebar at the time of writing)
