### ISSUE TITLE
Weird twitching

### ISSUE THREAD

**Issue by Naezr** [sirlan-ff00ff/arcticfox-theme#8]
As I understand it, if you move the cursor over this place, the :hover attribute disappears for a millisecond and the sidebar starts to close, but it doesn't have time because of the animation. If you disable the animation, the sidebar will just disappear instead of twitching.

![afafasfsdaf](https://github.com/sirlan-ff00ff/arcticfox-theme/assets/95460152/d7fc51e0-c02a-4046-9d57-8fdddb4df1dc)

**Comment by sirlan-ff00ff** [comment]
I'm not able to reproduce this, at least on Linux, it doesn't twitch when keeping the cursor anywhere in the header*, might try later on Windows to see if it is something with its header

**Comment by sirlan-ff00ff** [comment]
Ok, am able to reproduce on Windows, some quick test notes on behavior

- it doesn't happen in fulls screen mode
- trying to expand `#sidebar-box` to be either be under or cover the `#navigator-toolbox` doesn't change it, so it seems that area in general has the focus counted as lost for a few milliseconds
- it also happens with the 'old' style of resizing the page instead of overlaying, though it's slightly less dramatic
- adding more `:hover` rules doesn't seem to help
- removing `:hover` rules doesn't seem to help
- trying to revert some things doesn't seem to help

I don't really know what this could be besides some specific way Firefox handles header focus on Window, would then have to test some other themes that animate the header bar to see if this same jitter applies to them

**Comment by Naezr** [comment]
I tried it in linux and there really is no such twitching. Another little reason for me to switch to linux.
